
//Actions types for shifts
export const GET_SHIFTS_SUCCESS = 'GET_SHIFTS_SUCCESS';
export const SHIFTS_IS_LOADING = 'SHIFTS_IS_LOADING';
export const SHIFTS_HAS_ERRORED = 'SHIFTS_HAS_ERRORED';

export const ADD_SHIFT_SUCCESS = 'ADD_SHIFT_SUCCESS';
export const ADD_SHIFT_FAILURE = 'ADD_SHIFT_FAILURE';
export const ADD_SHIFT_STARTED = 'ADD_SHIFT_STARTED'; 

export const ASSIGN_SHIFT = 'ASSIGN_SHIFT';
export const CANCEL_SHIFT = 'CANCEL_SHIFT';
export const DELETE_SHIFT = 'DELETE_SHIFT';


//Actions types for positions
export const GET_POSITIONS = 'GET_POSITIONS_SUCCESS';
export const POSITIONS_IS_LOADING = 'POSITIONS_IS_LOADING';
export const POSITIONS_HAS_ERRORED = 'POSITIONS_HAS_ERRORED';

//Actions for employees
export const GET_EMPLOYEES_FOR_AUTOCOMPLETE_SUCCESS = 'GET_EMPLOYEES_FOR_AUTOCOMPLETE_SUCCESS';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const EMPLOYEES_IS_LOADING = 'EMPLOYEES_IS_LOADING';
export const EMPLOYEES_HAS_ERRORED = 'EMPLOYEES_HAS_ERRORED';

//Actions for modal
export const MODAL_HAS_CHANGED = 'MODAL_HAS_CHANGED';